ci: an attemp to fix deploy configuration

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,7 +22,11 @@ jobs:
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
           set -e
 
-          cd ~/../home/vanilla-http-web-server
+          echo "PWD: $(pwd)"
+          eoch "User: $(whoami)"
+          cd "../../../vanilla-http-web-server" || (echo "Directory not found" && exit 1)
+          echo "Success"
+          ls -la
 
           CURRENT_PORT=$(ss -tuln | grep ":500[01]" | grep "LISTEN" | awk "${print \$5}" | cut -d":" -f2 | head n1)
 
